<div>
          <span>Director</span>
          <span>{data.Director}</span>
        </div>
        <div>
          <span>starrs</span>
          <span>{data.Actors}</span>
        </div>
        <div>
          <span>Genrer</span>
          <span>{data.Genre}</span>
        </div>
        <div>
          <span>Lnaguage</span>
          <span>{data.Language}</span>
        </div>
        <div>
          <span>Awards</span>
          <span>{data.Awards}</span>
      </div>
     </div>
     </div>
  </div>
 </div>

    )
}